src/Entity/Message.php
<?php

namespace App\Entity;

use App\Service\MessageInterface;
use App\Service\ThreadInterface;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MessageRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Message implements MessageInterface
{
    /**
     * @var integer
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string
     * @Assert\NotBlank()
     * @Assert\Length(max="255")
     * @ORM\Column(name="body", type="string", length=255)
     */
    private $body;

    /**
     * @var \DateTimeInterface
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $createdAt;

    /**
     * @var boolean
     * @ORM\Column(name="seen", type="boolean", nullable=false)
     */
    private $read;

    /**
     * @var ThreadInterface
     * @ORM\ManyToOne(targetEntity="App\Entity\Thread", inversedBy="messages", cascade={"persist"})
     * @ORM\JoinColumn(name="thread_id", referencedColumnName="id")
     */
    private $thread;

    /**
     * @var UserInterface
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="messages", fetch="EAGER", cascade={"persist"})
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     */
    private $user;

    /**
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param string $body
     * @return $this
     */
    public function setBody(string $body)
    {
        $this->body = $body;
        return $this;
    }

    /**
     * @return string
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * @return $this
     */
    public function setCreatedAt()
    {
        $this->createdAt = new \DateTime();
        return $this;
    }

    /**
     * @return \DateTimeInterface
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * @return ThreadInterface
     */
    public function getThread()
    {
        return $this->thread;
    }

    /**
     * @param ThreadInterface $thread
     * @return $this
     */
    public function setThread(ThreadInterface $thread)
    {
        $this->thread = $thread;
        return $this;
    }

    /**
     * @return UserInterface
     */
    public function getOwner()
    {
        return $this->user;
    }

    /**
     * @param UserInterface $user
     * @return $this
     */
    public function setOwner(UserInterface $user)
    {
        $this->user = $user;
        return $this;
    }

    /**
     * @return bool
     */
    public function isRead()
    {
        return $this->read;
    }

    /**
     * @param bool $read
     * @return $this
     */
    public function setRead(bool $read)
    {
        $this->read = $read;
        return $this;
    }
}

src/Controller/CommunicationController.php
<?php

namespace App\Controller;

use App\Entity\Message;
use App\Entity\Thread;
use App\Event\MessageCreateEvent;
use App\Event\MessageReplyEvent;
use App\Event\MessageSeenEvent;
use App\Form\NewThreadMessageFormType;
use App\Form\ReplyMessageType;
use App\Provider\CommunicationProvider;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

class CommunicationController extends Controller
{
    public function showInbox(CommunicationProvider $communicationManager)
    {
        $threads = $communicationManager->getThreadsByUser($this->getUser());

        return $this->render('communication/index.html.twig', ['threads' => $threads]);
    }

    public function showThread(Thread $thread, Request $request)
    {
        $this->denyAccessUnlessGranted('show_communication', $thread);

        $message = new Message();
        $form = $this->createForm(ReplyMessageType::class, $message);

        $messageSeenEvent = new MessageSeenEvent($thread, $this->getUser());
        $this->get('event_dispatcher')->dispatch('communication.shown', $messageSeenEvent);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();

            $messageReplyEvent = new MessageReplyEvent($message, $thread, $this->getUser());
            $this->get('event_dispatcher')->dispatch('communication.reply', $messageReplyEvent);

            $em->persist($message);
            $em->flush();
            return $this->redirectToRoute('show_communication', ['id' => $thread->getId()]);
        }

        return $this->render('communication/show_thread.html.twig', [
            'thread' => $thread,
            'form' => $form->createView(),
        ]);
    }

    public function newMessage(Request $request)
    {
        $message = new Message();
        $form = $this->createForm(NewThreadMessageFormType::class, $message, [
            'user' => $this->getUser(),
        ]);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();

            $messageCreateEvent = new MessageCreateEvent($form, $message, $this->getUser());
            $this->get('event_dispatcher')->dispatch('communication.create', $messageCreateEvent);

            $em->persist($message);
            $em->flush();

            return $this->redirectToRoute('index_communication');
        }

        return $this->render('communication/new_thread.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    public function deleteThread(Request $request, Thread $thread)
    {
        $this->denyAccessUnlessGranted('delete_thread', $thread);
        if ($this->isCsrfTokenValid('delete' . $thread->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($thread);
            $em->flush();
        }

        return $this->redirectToRoute('index_communication');
    }

    public function deleteMessage(Request $request, Message $message)
    {
        $this->denyAccessUnlessGranted('delete_message', $message);
        if ($this->isCsrfTokenValid('delete' . $message->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($message);
            $em->flush();
        }

        return $this->redirectToRoute('index_communication');
    }
}

templates/communication/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} Inbox {% endblock %}

{% block body %}
    <div>
        <table class="table">
            <thead class="thead-dark">
            <tr>
                <th>Subject</th>
                <th>With</th>
                <th>Message</th>
                <th>Last message</th>
                <th>Actions</th>
            </tr>
            </thead>

            <tbody>

            {% if threads %}
                {% for thread in threads %}
                    <tr>
                        <td>
                            <a href="{{ path('show_communication', {'id': thread.id}) }}">
                                {{ thread.subject }}
                            </a>
                        </td>
                        <td>{% for participant in thread.participants %}
                                {% if participant is not same as(app.user) %}
                                    {{ participant.name }}
                                {% endif %}
                            {% endfor %}
                        </td>
                        <td>
                            {{ thread.messages|length }}
                        </td>
                        <td>{{ thread.messages.last.createdAt|date('Y-m-d H:i:s') }} By {{ thread.messages.last.owner.name }}</td>
                        <td>
                            <form method="post" action="{{ path('delete_thread', {'id': thread.id}) }}"
                                  onsubmit="return confirm('Are you sure you want to delete this item?');">
                                <input type="hidden" name="_method" value="DELETE">
                                <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ thread.id) }}">
                                <button class="btn">Delete Thread</button>
                            </form>
                        </td>
                        <td>

                        </td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="6">
                        No threads
                    </td>
                </tr>
            {% endif %}
            </tbody>
        </table>
    </div>

    <a href="{{ path('new_message') }}">New message</a>
{% endblock %}

templates/communication/new_thread.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<h2>New Message</h2>
<form action="{{ path('new_message') }}" method="POST">
    {{ form_start(form) }}
    {{ form_end(form) }}
</form>

{% endblock %}

templates/communication/show_thread.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h2>Subject: {{ thread.subject }}</h2>
    <h3>History:</h3>
    {% set messages = thread.messages|reverse %}
    {% for message in messages %}
        <div>
            <div>
                <tr>{% if app.user.name is same as(message.owner.name) %}
                        By {% trans %}You {% endtrans %}
                    {% else %}
                        By {{ message.owner.name|e }}
                    {% endif %}
                </tr>
                <tr>
                    on {{ message.createdAt|date }}
                    {% if app.user is same as (message.owner) %}
                        <form method="post" action="{{ path('delete_message', {'id': message.id}) }}"
                              onsubmit="return confirm('Are you sure you want to delete this item?');">
                            <input type="hidden" name="_method" value="DELETE">
                            <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ message.id) }}">
                            <button class="btn btn-sm btn-danger">DELETE</button>
                        </form>
                    {% endif %}

                </tr>
            </div>
            <div>
                {{ message.body }}
            </div>
        </div>
    {% endfor %}

    <h3>Reply</h3>

    <form action="{{ path('show_communication', {'id': thread.id}) }}" method="post">
        {{ form_widget(form) }}
        <input type="submit"/>
    </form>

{% endblock %}